### ISSUE TITLE
Lib can't use resolve.alias when playground import

### ISSUE THREAD

**Issue by busyhe** [LinusBorg/vue-lib-template#4]
<img width="885" alt="Xnip2023-04-20_15-10-35" src="https://user-images.githubusercontent.com/17348825/233288186-336f9929-1044-46a9-bf0a-2198f67c94e0.png">

**Comment by LinusBorg** [comment]
I'm sorry but I don't understand what problem you are trying to describe.

**Comment by busyhe** [comment]
This is an example. https://github.com/LinusBorg/vue-lib-template/compare/main...busyhe:vue-lib-template:main. If this method is used, for example resolve.alias will not be available.

**Comment by LinusBorg** [comment]
Ah, get I get it.

The playground is configured in a way that it directly imports the lib's sources in dev, so that you don't have to have a watched build process running for the lib.

But that also means that any aliases in the lib are interpreted in the context of the playground's vite alias settings.

One Solution would be to change the playground config to resolve `@/` aliases to the /lib/src/ directoy, and use a different alias in the playground app's files, i.e. `~/`.

As a recommendation though: If you intend to build and publish your lib with types, then don't use any aliases in the lib's source. Typescript will keep these alias paths in the generated `.d.ts` files, which won't be properly resolved in the consumer's project as their `tsconfig.json` won't have these aliases configured in the `"path"` option.
